# DB Connection - INF514 Z06
dburl=jdbc:mysql://127.0.0.1:3306/sakila
dbcatalog=sakila
dbuser=root
dbpassword=Welcome02$
dbdriver=com.mysql.cj.jdbc.Driver

# SSL
dbuseSSL=true
dbrequireSSL=false
dbverifyServerCertificate=false
dbsslMode=PREFERRED
dbtlsVersions=TLSv1.2,TLSv1.3